[build]
  base = "client"
  publish = "client/build"
  command = "npm ci && npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_DAILY_DOMAIN = "generativedialogue.daily.co"
  REACT_APP_USE_DAILY_API = "true"
